version: "3"
services:
    mongodb: 
        image: "mongo"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123456
        networks: 
            - bridge-1
        expose: 
            - "27017"
networks:  
    bridge-1:  
        external: true