version: "3"
services:
    php-fpm:
        image: "soen/php:fpm-7.3-alpine-all"
        networks: 
            - bridge-1
        volumes: 
            - F:\phpStudy\PHPTutorial\WWW:/home/www-data
            - F:\phpStudy\PHPTutorial\docker\php-fpm\etc\php:/usr/local/etc/php
            - F:\phpStudy\PHPTutorial\docker\php-fpm\softs:/home/softs
        expose: 
            - "9000"
        command: 
            - php-fpm
    swoole: 
        image: soen/php-swoole:2.0
        networks:
            - bridge-1
        volumes: 
            - F:\phpStudy\PHPTutorial\WWW:/home/www-data
            - F:\phpStudy\PHPTutorial\docker\swoole\etc\php:/usr/local/etc/php
            - F:\phpStudy\PHPTutorial\docker\swoole\softs:/home/softs
        expose: 
            - "9501"
        tty: true
        command: 
            - sh
    nginx: 
        image: "nginx:1.17.6-alpine"
        networks: 
            - bridge-1
        volumes: 
            - F:\phpStudy\PHPTutorial\WWW:/home/www-data
            - F:\phpStudy\PHPTutorial\docker\nginx\logs:/var/log/nginx
            - F:\phpStudy\PHPTutorial\docker\nginx\conf.d:/etc/nginx/conf.d
        ports: 
            - "80:80"
    redis: 
        image: "redis:alpine"
        networks: 
            - bridge-1
        expose: 
            - "6379"  
networks:  
    bridge-1:  
        external: true
        
        

