version: '3'
services:
    filebeat: 
    image: docker.elastic.co/beats/filebeat:7.6.1
    user: root
    environment: 
        - BEAT_STRICT_PERMS=false
    volumes: 
        - F:\phpStudy\PHPTutorial\docker\filebeat\filebeat.yml:/usr/share/filebeat/filebeat.yml
        - F:\phpStudy\PHPTutorial\docker\filebeat\logs:/usr/share/filebeat/logs
        - F:\phpStudy\PHPTutorial\docker\filebeat\data:/usr/share/filebeat/data
        ##为了读取外部的日志文件，开启共享，下面举例为读取外部Nginx的/var/logs/nginx里的日志
        - F:\phpStudy\PHPTutorial\docker\nginx\logs:/var/log/nginx

networks:
  elk:
    external: true